from __future__ import annotations

from expr_simplifier.transforms.constant_folding import apply_constant_folding as apply_constant_folding
from expr_simplifier.transforms.cse import apply_cse as apply_cse
from expr_simplifier.transforms.remove_named_expr import apply_remove_named_expr as apply_remove_named_expr
